# Global settings applied to the whole site.  
# “base” is directory to change to before starting build, and
# “public” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = ""
  publish = "build"
  command = "node fuser-client.js  --build  --env=prod" # define `secret` env var in netlify console
  #  && gulp firebase-deploy-functions
  #command = "gulp build --prod && gulp firebase-deploy-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
